(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const c of e)if(c.type==="childList")for(const l of c.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const c={};return e.integrity&&(c.integrity=e.integrity),e.referrerPolicy&&(c.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?c.credentials="include":e.crossOrigin==="anonymous"?c.credentials="omit":c.credentials="same-origin",c}function o(e){if(e.ep)return;e.ep=!0;const c=r(e);fetch(e.href,c)}})();const $=async(t,s,r)=>await(await fetch(`https://app.ticketmaster.com/discovery/v2/events.json?apikey=Z85ENznHLZiiD4emV1glh7STR86oVhNw&keyword=${encodeURIComponent(t)}&countryCode=${s}&page=${r}`)).json(),a=document.querySelector(".hero__input"),w=document.querySelector(".cards__list"),d=document.querySelector(".hero__country"),f=document.querySelector(".cards__schedule");let n=0,i=1;async function m(t=0){var s,r,o;try{const e=await $((a==null?void 0:a.value)||"",(d==null?void 0:d.value)||"",t),c=((s=e==null?void 0:e._embedded)==null?void 0:s.events)||[];i=((r=e==null?void 0:e.page)==null?void 0:r.totalPages)>50?50:((o=e==null?void 0:e.page)==null?void 0:o.totalPages)||1,n=t;const l=c.map(u=>{var _,h,y,v,L,b,P;return`
        <li class="cards__item">
            <img src="${((h=(_=u.images)==null?void 0:_[0])==null?void 0:h.url)||"/img/placeholderimg.png"}" 
                 alt="${u.name}"
                 class="cards__img">
            <div class="cards__item-contentb">
                <h1 class="cards__title">${u.name}</h1>
                <h2 class="cards__subtitle">${((v=(y=u.dates)==null?void 0:y.start)==null?void 0:v.localDate)||""}</h2>
                <p class="cards__text">
                    <svg class="cards__svg"><use href="/img/symbol-defs.svg#icon-arrow"></use></svg>
                    ${((P=(b=(L=u._embedded)==null?void 0:L.venues)==null?void 0:b[0])==null?void 0:P.name)||"Unknown Venue"}
                </p>
            </div>
        </li>`}).join("");w.innerHTML=l,k()}catch(e){console.error("Помилка:",e),w.innerHTML="<p>Помилка завантаження даних.</p>",f.innerHTML=""}}function k(){if(f.innerHTML="",i<=1)return;let t,s;i<=5?(t=0,s=i):n<=2?(t=0,s=5):n+2>=i?(t=i-5,s=i):(t=n-2,s=n+3);for(let r=t;r<s;r+=1){const o=document.createElement("li");o.className=`cards__schedule-item ${r===n?"active-page":""}`,o.innerHTML=`<p class="cards__schedule-text">${r+1}</p>`,o.addEventListener("click",()=>{r!==n&&(window.scrollTo({top:0,behavior:"smooth"}),m(r))}),f.appendChild(o)}}m(0);a==null||a.addEventListener("change",()=>m(0));d==null||d.addEventListener("change",()=>m(0));const g=document.querySelector(".backdrop"),S=document.querySelector(".modal__close"),T=document.querySelector(".cards__list");function p(){g.classList.toggle("is__hidden"),document.body.classList.toggle("no-scroll")}T.addEventListener("click",t=>{t.target.closest(".cards__item")&&p()});S&&S.addEventListener("click",p);g.addEventListener("click",t=>{t.target===g&&p()});
//# sourceMappingURL=commonHelpers.js.map
